package com.stockflow.stockflowbackend.subscription;

public enum SubscriptionFeature {
    CUSTOMER_HISTORY,
    AUTO_REORDER,
    ADVANCED_REPORTS,
    STOCK_RESERVATION,
    DELIVERY_SCHEDULING,
    INVOICE_GENERATION,
    INVOICE_DELIVERY,
    MARKETPLACE_LISTING,
    CREDIT_CONTACT_INFO,
    INVOICE_ON_DEMAND,
    RECENT_ACTIVITY_FEED
}
