"use client"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"

const API_BASE_URL = "https://stockflow-backend-qwpt.onrender.com"

export default function PrintInvoicesPage() {
  const router = useRouter()
  const [user, setUser] = useState<any>(null)
  const [invoices, setInvoices] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const stored = localStorage.getItem("sf_user")
    if (!stored) { router.replace("/login"); return }
    const u = JSON.parse(stored)
    setUser(u)
    fetchInvoices(u)
  }, [])

  const fetchInvoices = async (u: any) => {
    try {
      const token = localStorage.getItem("sf_token")
      const headers: any = {}
      if (token) headers.Authorization = `Bearer ${token}`
      const res = await fetch(`${API_BASE_URL}/pos/invoices`, { headers })
      const data = await res.json()
      setInvoices(data?.content || data || [])
      setTimeout(() => window.print(), 500)
    } catch (e) {
      setInvoices([])
    } finally {
      setLoading(false)
    }
  }

  if (!user || loading) return null

  const total = invoices.reduce((sum: number, i: any) => sum + Number(i.totalUsd || 0), 0)

  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', maxWidth: '800px', margin: '0 auto', padding: '48px 32px', color: '#0f172a' }}>
      <style>{`@media print { button { display: none !important; } }`}</style>

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '48px' }}>
        <div>
          <h1 style={{ fontSize: '28px', fontWeight: 800, marginBottom: '4px' }}>Invoice Report</h1>
          <p style={{ fontSize: '14px', color: '#64748b' }}>{user.businessName} · {new Date().toLocaleDateString()}</p>
        </div>
        <button onClick={() => router.back()} style={{ padding: '10px 20px', borderRadius: '10px', border: '1px solid #e2e8f0', backgroundColor: '#ffffff', cursor: 'pointer', fontSize: '13px', fontWeight: 600 }}>
          ← Back
        </button>
      </div>

      {invoices.length === 0 ? (
        <p style={{ textAlign: 'center', color: '#94a3b8', padding: '40px 0' }}>No invoices to display.</p>
      ) : (
        <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '32px' }}>
          <thead>
            <tr style={{ borderBottom: '2px solid #0f172a' }}>
              {['Invoice ID', 'Party', 'Date', 'Amount', 'Status'].map(h => (
                <th key={h} style={{ textAlign: 'left', padding: '10px 12px', fontSize: '12px', fontWeight: 700, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {invoices.map((inv: any, i: number) => {
              const status = inv.status || (inv.paymentMode === "CREDIT" ? "UNPAID" : "PAID")
              return (
                <tr key={inv.transactionId || inv.id || i} style={{ borderBottom: '1px solid #f1f5f9', backgroundColor: i % 2 === 0 ? '#ffffff' : '#f8fafc' }}>
                  <td style={{ padding: '14px 12px', fontSize: '13px', fontFamily: 'monospace' }}>{inv.invoiceNumber}</td>
                  <td style={{ padding: '14px 12px', fontSize: '13px', fontWeight: 600 }}>{inv.productName || inv.buyerName || "Sale"}</td>
                  <td style={{ padding: '14px 12px', fontSize: '13px', color: '#64748b' }}>{inv.recordedAt ? new Date(inv.recordedAt).toLocaleDateString() : ""}</td>
                  <td style={{ padding: '14px 12px', fontSize: '13px', fontWeight: 700 }}>${Number(inv.totalUsd || 0).toLocaleString()}</td>
                  <td style={{ padding: '14px 12px' }}>
                    <span style={{
                      fontSize: '11px', fontWeight: 700, padding: '3px 10px', borderRadius: '6px',
                      backgroundColor: status === 'PAID' ? '#ecfdf5' : status === 'OVERDUE' ? '#fef2f2' : '#f8fafc',
                      color: status === 'PAID' ? '#059669' : status === 'OVERDUE' ? '#dc2626' : '#64748b',
                    }}>
                      {status}
                    </span>
                  </td>
                </tr>
              )
            })}
          </tbody>
          <tfoot>
            <tr style={{ borderTop: '2px solid #0f172a' }}>
              <td colSpan={3} style={{ padding: '14px 12px', fontWeight: 700, fontSize: '14px' }}>Total</td>
              <td colSpan={2} style={{ padding: '14px 12px', fontWeight: 800, fontSize: '18px', color: '#1a56db' }}>${total.toLocaleString()}</td>
            </tr>
          </tfoot>
        </table>
      )}

      <p style={{ fontSize: '12px', color: '#94a3b8', textAlign: 'center' }}>Generated by StockFlow Pro · {user.businessName} · {new Date().toLocaleDateString()}</p>
    </div>
  )
}
