"use client"
import { useState, useEffect } from "react"
import { useRouter } from "next/navigation"
import { ArrowLeft, FileText, Calendar, TrendingUp, Download, Share2 } from "lucide-react"
import { toast } from "sonner"
import { API_BASE_URL } from "@/lib/api"

const STATUS_CONFIG: Record<string, { bg: string; text: string; border: string; dot: string }> = {
  PAID: { bg: '#ecfdf5', text: '#059669', border: '#a7f3d0', dot: '#059669' },
  UNPAID: { bg: '#f8fafc', text: '#64748b', border: '#e2e8f0', dot: '#94a3b8' },
  OVERDUE: { bg: '#fef2f2', text: '#dc2626', border: '#fecaca', dot: '#dc2626' },
}

export default function InvoicesPage() {
  const router = useRouter()
  const [user, setUser] = useState<any>(null)
  const [invoices, setInvoices] = useState<any[]>([])
  const [filter, setFilter] = useState("ALL")
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const stored = localStorage.getItem("sf_user")
    if (!stored) { router.replace("/login"); return }
    const u = JSON.parse(stored)
    setUser(u)
    fetchInvoices(u)
  }, [])

  const fetchInvoices = async (u: any) => {
    try {
      const token = localStorage.getItem("sf_token")
      const headers: any = {}
      if (token) headers.Authorization = `Bearer ${token}`
      const res = await fetch(`${API_BASE_URL}/pos/invoices`, { headers })
      const data = await res.json()
      setInvoices(data?.content || data || [])
    } catch (e) {
      setInvoices([])
    } finally {
      setLoading(false)
    }
  }

  if (!user) return null

  const filtered = filter === "ALL" ? invoices : invoices.filter((i: any) => (i.status || (i.paymentMode === "CREDIT" ? "UNPAID" : "PAID")) === filter)
  const total = invoices.reduce((sum: number, i: any) => sum + Number(i.totalUsd || 0), 0)
  const paid = invoices.filter((i: any) => (i.status || (i.paymentMode === "CREDIT" ? "UNPAID" : "PAID")) === "PAID").reduce((sum: number, i: any) => sum + Number(i.totalUsd || 0), 0)
  const outstanding = invoices.filter((i: any) => (i.status || (i.paymentMode === "CREDIT" ? "UNPAID" : "PAID")) !== "PAID").reduce((sum: number, i: any) => sum + Number(i.totalUsd || 0), 0)

  const shareInvoice = async (inv: any) => {
    const status = inv.status || (inv.paymentMode === "CREDIT" ? "UNPAID" : "PAID")
    const text = `Invoice ${inv.invoiceNumber}\n${inv.buyerName || inv.buyerBusinessName || "Sale"}\nDate: ${inv.createdAt ? new Date(inv.createdAt).toLocaleDateString() : ""}\nAmount: $${Number(inv.totalUsd || 0).toFixed(2)}\nStatus: ${status}\nPayment mode: ${inv.paymentMode}\n\nGenerated by StockFlow Pro`
    if (typeof navigator !== "undefined" && (navigator as any).share) {
      try {
        await (navigator as any).share({ title: `Invoice ${inv.invoiceNumber}`, text })
        return
      } catch {
        return
      }
    }
    try {
      await navigator.clipboard.writeText(text)
      toast.success("Invoice details copied to clipboard")
    } catch {
      toast.error("Couldn't share this invoice")
    }
  }

  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#f8fafc' }}>
      <header style={{ backgroundColor: '#ffffff', borderBottom: '1px solid #f1f5f9', padding: '0 24px', boxShadow: '0 1px 8px rgba(0,0,0,0.04)' }}>
        <div style={{ maxWidth: '1000px', margin: '0 auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: '64px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
            <button onClick={() => router.push("/dashboard")} style={{ width: '36px', height: '36px', borderRadius: '10px', backgroundColor: '#f8fafc', border: '1px solid #e2e8f0', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' }}>
              <ArrowLeft style={{ width: '16px', height: '16px', color: '#64748b' }} />
            </button>
            <div>
              <p style={{ fontWeight: 700, fontSize: '16px', color: '#0f172a' }}>Invoices</p>
              <p style={{ fontSize: '11px', color: '#94a3b8' }}>{invoices.length} invoices total</p>
            </div>
          </div>
          <button onClick={() => router.push("/invoices/print")} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 18px', borderRadius: '12px', background: 'linear-gradient(135deg, #1a56db, #4f46e5)', color: '#ffffff', fontWeight: 600, fontSize: '13px', border: 'none', cursor: 'pointer', boxShadow: '0 4px 12px rgba(26,86,219,0.3)' }}>
            <Download style={{ width: '14px', height: '14px' }} />Export
          </button>
        </div>
      </header>

      <main style={{ maxWidth: '1000px', margin: '0 auto', padding: '32px 24px' }}>
        {loading ? (
          <div style={{ textAlign: 'center', padding: '60px 0', color: '#94a3b8' }}>Loading...</div>
        ) : invoices.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '60px 0', color: '#94a3b8' }}>
            <FileText style={{ width: '40px', height: '40px', margin: '0 auto 12px', color: '#d1d5db' }} />
            <p style={{ fontWeight: 600, color: '#374151' }}>No invoices yet</p>
            <p style={{ fontSize: '13px', marginTop: '4px' }}>Invoices are generated automatically from POS sales</p>
          </div>
        ) : (
          <>
            {/* Summary cards */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '16px', marginBottom: '28px' }}>
              {[
                { label: "Total invoiced", value: `$${total.toLocaleString()}`, icon: FileText, color: '#1a56db', bg: '#eff6ff' },
                { label: "Paid", value: `$${paid.toLocaleString()}`, icon: TrendingUp, color: '#059669', bg: '#ecfdf5' },
                { label: "Outstanding", value: `$${outstanding.toLocaleString()}`, icon: Calendar, color: '#dc2626', bg: '#fef2f2' },
              ].map(s => (
                <div key={s.label} style={{ backgroundColor: '#ffffff', borderRadius: '16px', padding: '20px', border: '1px solid #f1f5f9', boxShadow: '0 2px 8px rgba(0,0,0,0.03)' }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px' }}>
                    <p style={{ fontSize: '11px', color: '#94a3b8', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.06em' }}>{s.label}</p>
                    <div style={{ width: '32px', height: '32px', borderRadius: '9px', backgroundColor: s.bg, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      <s.icon style={{ width: '14px', height: '14px', color: s.color }} />
                    </div>
                  </div>
                  <p style={{ fontSize: '22px', fontWeight: 800, color: '#0f172a' }}>{s.value}</p>
                </div>
              ))}
            </div>

            {/* Filters */}
            <div style={{ display: 'flex', gap: '8px', marginBottom: '20px' }}>
              {["ALL", "PAID", "UNPAID", "OVERDUE"].map(f => (
                <button key={f} onClick={() => setFilter(f)} style={{
                  padding: '8px 16px', borderRadius: '10px', fontSize: '12px', fontWeight: 600,
                  cursor: 'pointer', border: 'none', transition: 'all 0.2s',
                  backgroundColor: filter === f ? '#0f172a' : '#ffffff',
                  color: filter === f ? '#ffffff' : '#64748b',
                  boxShadow: filter === f ? '0 2px 8px rgba(0,0,0,0.15)' : '0 1px 3px rgba(0,0,0,0.06)',
                }}>
                  {f === "ALL" ? "All" : f.charAt(0) + f.slice(1).toLowerCase()}
                </button>
              ))}
            </div>

            {/* Invoice list */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              {filtered.map((inv: any) => {
                const status = inv.status || (inv.paymentMode === "CREDIT" ? "UNPAID" : "PAID")
                const sc = STATUS_CONFIG[status] || STATUS_CONFIG.UNPAID
                return (
                  <div key={inv.id} style={{
                    backgroundColor: '#ffffff', borderRadius: '16px', padding: '20px 24px',
                    border: '1px solid #f1f5f9', boxShadow: '0 2px 8px rgba(0,0,0,0.03)',
                    display: 'flex', alignItems: 'center', gap: '16px',
                    transition: 'all 0.2s', cursor: 'pointer',
                  }}
                    onMouseEnter={e => (e.currentTarget as HTMLDivElement).style.boxShadow = '0 4px 20px rgba(0,0,0,0.08)'}
                    onMouseLeave={e => (e.currentTarget as HTMLDivElement).style.boxShadow = '0 2px 8px rgba(0,0,0,0.03)'}
                  >
                    <div style={{ width: '42px', height: '42px', borderRadius: '12px', backgroundColor: '#f8fafc', border: '1px solid #e2e8f0', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                      <FileText style={{ width: '18px', height: '18px', color: '#64748b' }} />
                    </div>
                    <div style={{ flex: 1 }}>
                      <p style={{ fontWeight: 700, fontSize: '14px', color: '#0f172a', marginBottom: '3px' }}>{inv.buyerName || inv.buyerBusinessName || "Sale"}</p>
                      <p style={{ fontSize: '12px', color: '#94a3b8', display: 'flex', alignItems: 'center', gap: '4px' }}>
                        <Calendar style={{ width: '11px', height: '11px' }} />{inv.createdAt ? new Date(inv.createdAt).toLocaleDateString() : ""} · <span style={{ fontFamily: 'monospace' }}>{inv.invoiceNumber}</span>
                      </p>
                    </div>
                    <div style={{ textAlign: 'right' }}>
                      <p style={{ fontWeight: 800, fontSize: '16px', color: '#0f172a', marginBottom: '6px' }}>${Number(inv.totalUsd || 0).toLocaleString()}</p>
                      <span style={{ fontSize: '11px', fontWeight: 700, padding: '4px 10px', borderRadius: '8px', backgroundColor: sc.bg, color: sc.text, border: `1px solid ${sc.border}` }}>
                        {status.charAt(0) + status.slice(1).toLowerCase()}
                      </span>
                    </div>
                    <button
                      onClick={e => { e.stopPropagation(); shareInvoice(inv) }}
                      title="Share invoice"
                      style={{ width: '36px', height: '36px', borderRadius: '10px', border: '1px solid #e2e8f0', backgroundColor: '#ffffff', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', flexShrink: 0 }}
                    >
                      <Share2 style={{ width: '15px', height: '15px', color: '#64748b' }} />
                    </button>
                  </div>
                )
              })}
            </div>
          </>
        )}
      </main>
    </div>
  )
}
