import { useState, useEffect, useCallback, useMemo } from 'react';
import { View, Text, TouchableOpacity, FlatList, StyleSheet, SafeAreaView, ActivityIndicator, RefreshControl, Share, Alert } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { api } from '../services/api';
import { useAuthStore } from '../store/authStore';
import { useThemeColors } from '../hooks/useThemeColors';
import { useCurrency } from '../hooks/useCurrency';
import { ThemeColors } from '../theme/colors';
import { StatusIndicator, urgencyBorder, UrgencyStatus } from '../components/StatusIndicator';
import { SkeletonRow } from '../components/Skeleton';

const STATUS_MAP = (colors: ThemeColors): Record<string, { bg: string; text: string; label: string }> => ({
  PAID: { bg: colors.successSurface, text: colors.successText, label: 'Paid' },
  UNPAID: { bg: colors.border, text: colors.textSecondary, label: 'Unpaid' },
  OVERDUE: { bg: colors.dangerSurface, text: colors.dangerText, label: 'Overdue' },
});

const URGENCY_MAP: Record<string, UrgencyStatus> = {
  PAID: 'ok',
  UNPAID: 'neutral',
  OVERDUE: 'danger',
};

export default function InvoicesScreen() {
  const router = useRouter();
  const { user } = useAuthStore();
  const { colors } = useThemeColors();
  const { format } = useCurrency();
  const s = useMemo(() => makeStyles(colors), [colors]);
  const STATUS = useMemo(() => STATUS_MAP(colors), [colors]);
  const [invoices, setInvoices] = useState<any[]>([]);
  const [filter, setFilter] = useState('ALL');
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const fetchInvoices = useCallback(async () => {
    try {
      const url = filter === 'ALL' ? '/pos/invoices' : `/pos/invoices?status=${filter}`;
      const res = await api.get(url);
      setInvoices(res.data?.content || res.data || []);
    } catch (e) {
      console.log('Error fetching invoices:', e);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [filter]);

  useEffect(() => { fetchInvoices(); }, [fetchInvoices]);

  const total = invoices.reduce((sum, i) => sum + Number(i.totalUsd || 0), 0);

  const shareInvoice = async (item: any) => {
    const status = item.status || (item.paymentMode === 'CREDIT' ? 'UNPAID' : 'PAID');
    const message =
      `Invoice ${item.invoiceNumber}\n` +
      `${item.buyerName || item.buyerBusinessName || 'Sale'}\n` +
      `Date: ${new Date(item.createdAt).toLocaleDateString()}\n` +
      `Amount: ${format(Number(item.totalUsd))}\n` +
      `Status: ${status}\n` +
      `Payment mode: ${item.paymentMode}\n\n` +
      `Generated by StockFlow Pro`;
    try {
      await Share.share({ message, title: `Invoice ${item.invoiceNumber}` });
    } catch (e) {
      Alert.alert('Error', 'Could not share this invoice.');
    }
  };

  if (loading) return (
    <SafeAreaView style={s.page}>
      <View style={s.header}>
        <TouchableOpacity onPress={() => router.back()} style={s.backBtn}>
          <Ionicons name="arrow-back-outline" size={20} color={colors.textPrimary} />
        </TouchableOpacity>
        <View>
          <Text style={s.title}>Invoices</Text>
        </View>
      </View>
      <View style={{ padding: 12, gap: 8 }}>
        {[1, 2, 3, 4, 5].map(i => <SkeletonRow key={i} />)}
      </View>
    </SafeAreaView>
  );

  return (
    <SafeAreaView style={s.page}>
      <View style={s.header}>
        <TouchableOpacity onPress={() => router.back()} style={s.backBtn}>
          <Ionicons name="arrow-back-outline" size={20} color={colors.textPrimary} />
        </TouchableOpacity>
        <View>
          <Text style={s.title}>Invoices</Text>
          <Text style={s.sub}>{invoices.length} invoices · {format(total)}</Text>
        </View>
      </View>

      <View style={s.body}>
        <View style={s.chips}>
          {['ALL', 'PAID', 'UNPAID', 'OVERDUE'].map(f => (
            <TouchableOpacity key={f} style={[s.chip, filter === f && s.chipActive]} onPress={() => setFilter(f)}>
              <Text style={[s.chipText, filter === f && s.chipTextActive]}>
                {f === 'ALL' ? 'All' : STATUS[f]?.label || f}
              </Text>
            </TouchableOpacity>
          ))}
        </View>

        <FlatList
          data={invoices}
          keyExtractor={item => String(item.id)}
          contentContainerStyle={{ gap: 8, paddingBottom: 100 }}
          showsVerticalScrollIndicator={false}
          refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); fetchInvoices(); }} tintColor={colors.primary} />}
          ListEmptyComponent={
            <View style={s.empty}>
              <Ionicons name="receipt-outline" size={40} color={colors.borderStrong} />
              <Text style={s.emptyText}>No invoices yet</Text>
              <Text style={s.emptySub}>Invoices are generated automatically from POS sales</Text>
              <TouchableOpacity
                style={s.emptyBtn}
                onPress={() => router.push((user?.tierType === 'WHOLESALER' ? '/(wholesaler)/pos' : '/(retailer)/pos') as any)}
              >
                <Ionicons name="add-circle-outline" size={16} color={colors.onPrimary} style={{ marginRight: 6 }} />
                <Text style={s.emptyBtnText}>New sale</Text>
              </TouchableOpacity>
            </View>
          }
          renderItem={({ item }) => {
            const status = item.status || (item.paymentMode === 'CREDIT' ? 'UNPAID' : 'PAID');
            const st = STATUS[status] || STATUS.UNPAID;
            const urgency = URGENCY_MAP[status] || 'neutral';
            return (
              <View style={[s.card, urgencyBorder(urgency, colors), urgency === 'danger' && { paddingLeft: 11 }]}>
                <View style={[s.cardIcon, { backgroundColor: st.bg }]}>
                  <Ionicons name="receipt-outline" size={18} color={st.text} />
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={s.party}>{item.buyerName || item.buyerBusinessName || 'Sale'}</Text>
                  <View style={s.row}>
                    <Ionicons name="calendar-outline" size={11} color={colors.textPlaceholder} />
                    <Text style={s.date}> {new Date(item.createdAt).toLocaleDateString()}</Text>
                  </View>
                  <Text style={s.invoiceId}>{item.invoiceNumber}</Text>
                </View>
                <View style={{ alignItems: 'flex-end', gap: 6 }}>
                  <Text style={s.amount}>{format(Number(item.totalUsd))}</Text>
                  <StatusIndicator status={urgency} label={st.label} />
                </View>
                <TouchableOpacity style={s.shareBtn} onPress={() => shareInvoice(item)}>
                  <Ionicons name="share-outline" size={16} color={colors.textMuted} />
                </TouchableOpacity>
              </View>
            );
          }}
        />
      </View>
    </SafeAreaView>
  );
}

const makeStyles = (colors: ThemeColors) => StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.bg },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: { backgroundColor: colors.surface, padding: 16, paddingBottom: 12, borderBottomWidth: 0.5, borderBottomColor: colors.border, flexDirection: 'row', alignItems: 'center', gap: 12 },
  backBtn: { width: 36, height: 36, borderRadius: 10, backgroundColor: colors.border, alignItems: 'center', justifyContent: 'center' },
  title: { fontSize: 18, fontWeight: '700', color: colors.textPrimary },
  sub: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  body: { flex: 1, padding: 12 },
  chips: { flexDirection: 'row', gap: 8, marginBottom: 12, flexWrap: 'wrap' },
  chip: { paddingVertical: 5, paddingHorizontal: 14, borderRadius: 20, backgroundColor: colors.surface, borderWidth: 0.5, borderColor: colors.border },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { fontSize: 12, color: colors.textSecondary },
  chipTextActive: { color: colors.onPrimary, fontWeight: '500' },
  card: { backgroundColor: colors.surface, borderRadius: 16, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 0.5, borderColor: colors.border },
  cardIcon: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  party: { fontSize: 13, fontWeight: '600', color: colors.textPrimary },
  row: { flexDirection: 'row', alignItems: 'center', marginTop: 2 },
  date: { fontSize: 11, color: colors.textPlaceholder },
  invoiceId: { fontSize: 10, color: colors.textPlaceholder, marginTop: 2 },
  amount: { fontSize: 14, fontWeight: '700', color: colors.textPrimary, marginBottom: 4 },
  shareBtn: { width: 32, height: 32, borderRadius: 16, backgroundColor: colors.border, alignItems: 'center', justifyContent: 'center', marginLeft: 8 },
  empty: { alignItems: 'center', paddingTop: 60, gap: 8 },
  emptyText: { fontSize: 16, fontWeight: '600', color: colors.textSecondary },
  emptySub: { fontSize: 13, color: colors.textPlaceholder, textAlign: 'center', paddingHorizontal: 40 },
  emptyBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.primary, borderRadius: 12, paddingVertical: 10, paddingHorizontal: 18, marginTop: 8 },
  emptyBtnText: { color: colors.onPrimary, fontSize: 13, fontWeight: '600' },
});